//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZ.Services.SrParceiro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrParceiro.IParceiroService")]
    internal interface IParceiroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParceiroService/Ping", ReplyAction="http://tempuri.org/IParceiroService/PingResponse")]
        bool Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IParceiroServiceChannel : XYZ.Services.SrParceiro.IParceiroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ParceiroServiceClient : System.ServiceModel.ClientBase<XYZ.Services.SrParceiro.IParceiroService>, XYZ.Services.SrParceiro.IParceiroService {
        
        public ParceiroServiceClient() {
        }
        
        public ParceiroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParceiroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParceiroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParceiroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
    }
}
